# Generated by Django 4.1.2 on 2022-10-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tanishq',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=90)),
                ('choice', models.CharField(max_length=90)),
                ('paymentMode', models.CharField(max_length=90)),
                ('image', models.ImageField(upload_to='media')),
                ('date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
